name: android-build

on:
  push:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool pkg-config \
            zip unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            python3-full python3-setuptools python3-venv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: List built APKs
        run: find . -name "*.apk"

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fencing-app
          path: ./bin/*.apk
