name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool pkg-config \
            zip unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            python3-full python3-setuptools python3-venv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer & p4a
        run: |
          pip install --upgrade pip setuptools cython buildozer python-for-android

      - name: Clean previous build
        run: buildozer android clean

      - name: Build APK
        run: yes | buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fencing-app-apk
          path: bin/*.apk
