name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool pkg-config \
            zip unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            openjdk-11-jdk python3.10 python3.10-venv python3.10-dev

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create & activate venv
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install Buildozer & python-for-android
        run: |
          pip install --upgrade pip setuptools cython buildozer python-for-android

      - name: Accept Android SDK licenses
        run: yes | buildozer android sdk --sdk --ndk --licenses

      - name: Clean any previous build
        run: buildozer android clean

      - name: Build APK
        run: |
          buildozer android debug --verbose

      - name: List APK(s)
        run: find . -type f -name "*.apk"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fencing-app-apk
          path: bin/*.apk
