name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool pkg-config \
            zip unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            python3-full python3-setuptools python3-venv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fencing-app-apk
          path: ./bin/*.apk

